-- this is generated by gpt 


-- Insert into class
INSERT INTO class (classId, classCode, floor) VALUES
(1, 'A101', 1),
(2, 'B202', 2),
(3, 'C303', 3);

-- Insert into users
INSERT INTO users (userId, email, passHash, phoneNum, usertype) VALUES
(1, 'alice@example.com', 'hash123', '555-1234', 'student'),
(2, 'bob@example.com', 'hash456', '555-5678', 'teacher'),
(3, 'carol@example.com', 'hash789', '555-9876', 'student'),
(4, 'admin@admin.com', 'hash789', '555-9876', 'admin'),
(5, 're@re.re', 'hash789', '555-9876', 'removed');

-- Insert into reservation
INSERT INTO reservation (reservationId, classId, duration, reservationDate, reservationUseDate) VALUES
(1, 1, 60, '2025-11-04', '2025-11-05'),
(2, 2, 90, '2025-11-03', '2025-11-06'),
(3, 3, 120, '2025-11-01', '2025-11-07');

-- Insert into joinuser
INSERT INTO joinuser (joinId, reservationId, userId) VALUES
(1, 1, 1),
(3, 2, 3),
(4, 3, 1);
